ruyi-repo = "v1"

[repo]
doc_uri = "https://ruyisdk.github.io/docs/"

[[mirrors]]
id = "ruyi-dist"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/dist/",
]

[[mirrors]]
id = "ruyi-3rdparty-canaan"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/3rdparty/canaan/",
]

[[mirrors]]
id = "ruyi-3rdparty-milkv"
urls = [
  "https://mirror.iscas.ac.cn/ruyisdk/3rdparty/milkv/",
]
