format = "v1"

[metadata]
desc = "Official CanMV Ubuntu SDK v1.3 image for Canaan Kendryte K230"
vendor = { name = "Canaan", eula = "" }

[[distfiles]]
name = "canmv_ubuntu_sdcard_1.3.img.gz"
size = 203496795
urls = [
  "https://kendryte-download.canaan-creative.com/developer/k230/canmv_ubuntu_sdcard_1.3.img.gz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "13e4d4421c66581157253af1640eebddcc5ce22006c162d50666205eab2756d2"
sha512 = "812e99f077b7d28888f73857bdecfaa1496f33230fba4b44b3605a0109578fad9dcebe9ec4c6ec612579d98b8e8f7d73f73d9f41eaa6f79ce2a6fe3c475c7d90"

[blob]
distfiles = [
  "canmv_ubuntu_sdcard_1.3.img.gz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "canmv_ubuntu_sdcard_1.3.img"
