ruyi-entity = "v0"

related = ["arch:riscv64"]
unique_among_type_during_traversal = true

[uarch]
id = "sifive-x280"
display_name = "SiFive X280"
arch = "riscv64"

[uarch.riscv]
isa = "rv64imafdcv_zfh_zba_zbb_zvfh_zvl512b"
