ruyi-entity = "v0"

related = ["arch:riscv64"]

[uarch]
id = "xuantie-c906"
display_name = "Xuantie C906"
arch = "riscv64"

[uarch.riscv]
isa = "rv64imafdc_xtheadba_xtheadbb_xtheadbs_xtheadcmo_xtheadcondmov_xtheadfmemidx_xtheadmac_xtheadmemidx_xtheadmempair_xtheadsync"
