format = "v1"

[metadata]
desc = "openEuler 23.09 v1 XFCE image for Milk-V Pioneer with SG2042"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "openEuler-23.09-V1-xfce-sg2042-preview-refreshed.img.zst"
size = 2357104043
urls = [
  "https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/SG2042/openEuler-23.09-V1-xfce-sg2042-preview-refreshed.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "fcc2e1dfdcc207de91c6522a9f4d58690c022d2094292320f1336dc03ec56a02"
sha512 = "dd45677aaa8ee63785c2ad418d9d105cf1a8078738fe2cfb73ee4f565294407f9bb8ba02bf2c4b77d185d95f8efe39b098a3674405857a4543460bb11c4e03c6"

[blob]
distfiles = [
  "openEuler-23.09-V1-xfce-sg2042-preview-refreshed.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "openEuler-23.09-V1-xfce-sg2042-preview-refreshed.img"
