ruyi-entity = "v0"

related = [
  "device-variant:milkv-duo@256m",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Milk-V Duo Official Arduino SDK (256M RAM, SD card)"
package_atoms = ["board-image/arduino-milkv-duo256m-sd"]
