ruyi-entity = "v0"

related = [
  "device-variant:milkv-duo@64m",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Milk-V Duo Official Arduino SDK (64M RAM, SD card)"
package_atoms = ["board-image/arduino-milkv-duo-sd"]
