ruyi-entity = "v0"

related = [
  "device-variant:pine64-star64@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Armbian for Pine64 Star64"
package_atoms = ["board-image/armbian-pine64-star64"]
