ruyi-entity = "v0"

related = [
  "device-variant:sipeed-licheervnano@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Sipeed LicheeRV Nano Official buildroot SDK (Linux & FreeRTOS)"
package_atoms = ["board-image/buildroot-sdk-sipeed-licheervnano"]
