ruyi-entity = "v0"

related = [
  "device-variant:milkv-duos@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Milk-V Duo S Official buildroot SDK (FreeRTOS, SD card)"
package_atoms = ["board-image/buildroot-sdk-milkv-duos-sd"]
