ruyi-entity = "v0"

related = [
  "device-variant:canaan-k230@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Canaan Kendryte K230 Official CanMV Ubuntu SDK"
package_atoms = ["board-image/canmv-ubuntu-sdk-canaan-k230"]
