ruyi-entity = "v0"

related = [
  "device-variant:milkv-mars-cm@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Milk-V Mars CM Official Debian Desktop SDK (SD card)"
package_atoms = ["board-image/debian-desktop-sdk-milkv-mars-cm-sd"]
