ruyi-entity = "v0"

related = [
  "device-variant:sipeed-lpi4a@16g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "openEuler RISC-V (XFCE) for Sipeed LicheePi 4A (16G RAM)"
package_atoms = [
  "board-image/oerv-sipeed-lpi4a-xfce",
  "board-image/uboot-oerv-sipeed-lpi4a-16g"
]
