ruyi-entity = "v0"

related = [
  "device-variant:milkv-pioneer@v1.1",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "openEuler RISC-V (XFCE) for Milk-V Pioneer"
package_atoms = ["board-image/oerv-sg2042-milkv-pioneer-xfce"]
