ruyi-entity = "v0"

related = [
  "device-variant:sipeed-lpi4a@8g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "openEuler RISC-V (headless) for Sipeed LicheePi 4A (8G RAM)"
package_atoms = [
  "board-image/oerv-sipeed-lpi4a-headless",
  "board-image/uboot-oerv-sipeed-lpi4a-8g"
]
