ruyi-entity = "v0"

related = [
  "device-variant:milkv-pioneer@v1.2",
  "device-variant:milkv-pioneer@v1.3",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "openEuler RISC-V (base system) for Milk-V Pioneer (rootfs on NVMe)"
package_atoms = ["board-image/oerv-sg2042-milkv-pioneer-base"]
postinst_msgid = "provisioner/oerv-milkv-pioneer-nvme"
