ruyi-entity = "v0"

related = [
  "device-variant:sifive-unmatched@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "OpenBSD riscv64"
package_atoms = ["board-image/openbsd-riscv64-live"]
