ruyi-entity = "v0"

related = [
  "device-variant:canaan-k510@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Canaan Kendryte K510 Official Buildroot SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-buildroot-sdk-canaan-k510"
