ruyi-entity = "v0"

related = [
  "device-variant:wch-ch32v305-evb@fbp6",
  "device-variant:wch-ch32v305-evb@gbu6",
  "device-variant:wch-ch32v305-evb@rbt6",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "WCH CH32V305 EVB RT-Thread SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-rtthread-wch-ch32v305-evb"
