ruyi-entity = "v0"

related = [
  "device-variant:wch-ch32v307-evb@rct6",
  "device-variant:wch-ch32v307-evb@wcu6",
  "device-variant:wch-ch32v307-evb@vct6",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "WCH CH32V307 EVB RT-Thread SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-rtthread-wch-ch32v307-evb"
