ruyi-entity = "v0"

related = [
  "device-variant:wch-ch32v103-evb@c6t6",
  "device-variant:wch-ch32v103-evb@c8t6",
  "device-variant:wch-ch32v103-evb@c8u6",
  "device-variant:wch-ch32v103-evb@r8t6",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "WCH CH32V103 EVB FreeRTOS PlatformIO SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-freertos-pio-wch-ch32v103-evb"
