ruyi-entity = "v0"

related = [
  "device-variant:sipeed-tangmega138kpro@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Sipeed Tang Mega 138K Pro FPGA & FreeRTOS SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-freertos-sipeed-tangmega138kpro"
