ruyi-entity = "v0"

related = [
  "device-variant:wch-ch32v208-evb@cbu6",
  "device-variant:wch-ch32v208-evb@gbu6",
  "device-variant:wch-ch32v208-evb@rbt6",
  "device-variant:wch-ch32v208-evb@wbu6",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "WCH CH32V208 EVB FreeRTOS SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-freertos-wch-ch32v208-evb"
