ruyi-entity = "v0"

related = [
  "device-variant:wch-ch582f-evb@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "WCH CH582F EVB FreeRTOS SDK (documentation-only)"
package_atoms = []
postinst_msgid = "provisioner/doc-freertos-wch-ch582f-evb"
