ruyi-entity = "v0"

related = [
  "device-variant:sipeed-lc4a@16g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "RevyOS for Sipeed Lichee Cluster 4A (16G RAM)"
package_atoms = [
  "board-image/revyos-sipeed-lc4a",
  "board-image/uboot-revyos-sipeed-lc4a-16g"
]
