ruyi-entity = "v0"

related = [
  "device-variant:milkv-meles@16g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "RevyOS image for Milk-V Meles using EMMC"
package_atoms = [
  "board-image/revyos-milkv-meles",
  "board-image/uboot-revyos-milkv-meles-16g"
]
