ruyi-entity = "v0"

related = [
  "device-variant:milkv-meles@8g",
  "pkg:board-image/revyos-milkv-meles",
  "pkg:board-image/uboot-revyos-milkv-meles-8g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "RevyOS image for Milk-V Meles (8G RAM) using EMMC"
package_atoms = [
  "board-image/revyos-milkv-meles",
  "board-image/uboot-revyos-milkv-meles-8g",
]
