ruyi-entity = "v0"

related = [
  "device-variant:sifive-unmatched@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Ubuntu Server for SiFive HiFive Unmatched"
package_atoms = ["board-image/ubuntu-server-riscv64-sifive-unmatched"]
