format = "v1"

[metadata]
desc = "RuyiSDK RISC-V Linux GNU Toolchain 20231118 (T-Head sources, built by PLCT)"
vendor = { name = "PLCT", eula = "" }
slug = "gnu-plct-xthead-20231118"

[[distfiles]]
name = "RuyiSDK-20231118-T-Head-Sources-HOST-riscv64-linux-gnu-riscv64-plctxthead-linux-gnu.tar.xz"
size = 272630776

[distfiles.checksums]
sha256 = "f4092c7981fa236afb9e56d9ccb1955d8c1baeb343a0462aa8956422c2a77485"
sha512 = "1fe2a9a4edf8ba488188c64c6d03960e2244e0c7a3ae6a4ddeff636a9738fa59f193b856f026fb23e2c2e97faa4745c76417dda7cbc9b173b6c98a417eeb2fc7"

[[distfiles]]
name = "RuyiSDK-20231118-T-Head-Sources-riscv64-plctxthead-linux-gnu.tar.xz"
size = 286881456

[distfiles.checksums]
sha256 = "0e81b1e2529d946f0c13d8d91c803236695a084cc98d419a7b6f8cfd3c6fb3b8"
sha512 = "3a3eddf758184d994badcddf754ccc5b9d50385017b05170028ef3bc2053d36dbe4ab1f585329cbf2b5c4c4b82895a383ef5159e37d13c87625c1598416479be"

[[binary]]
host = "riscv64"
distfiles = ["RuyiSDK-20231118-T-Head-Sources-HOST-riscv64-linux-gnu-riscv64-plctxthead-linux-gnu.tar.xz"]

[[binary]]
host = "x86_64"
distfiles = ["RuyiSDK-20231118-T-Head-Sources-riscv64-plctxthead-linux-gnu.tar.xz"]

[toolchain]
target = "riscv64-plctxthead-linux-gnu"
flavors = ["xthead"]
components = [
  { name = "binutils", version = "2.35" },
  { name = "gcc", version = "10.2.0" },
  { name = "gdb", version = "10.0" },
  { name = "glibc", version = "2.33" },
  { name = "linux-headers", version = "6.4" },
]
included_sysroot = "riscv64-plctxthead-linux-gnu/sysroot"
