ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:wch-ch32v203-evb"]
unique_among_type_during_traversal = true

[device-variant]
id = "g8r6"
variant_name = "CH32V203G8R6"
