ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:wch-ch32v103-evb"]
unique_among_type_during_traversal = true

[device-variant]
id = "c8u6"
variant_name = "CH32V103C8U6"
