ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc", "device:wch-ch32v307-evb"]
unique_among_type_during_traversal = true

[device-variant]
id = "wcu6"
variant_name = "CH32V307WCU6"
