ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc"]
unique_among_type_during_traversal = true

[device-variant]
id = "rct6"
variant_name = "CH32V307RCT6"
