format = "v1"

[metadata]
desc = "RuyiSDK QEMU linux-user Build (T-Head 6.1.0 commit 03813c9fe8, built by PLCT)"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "qemu-user-riscv-xthead-6.1.0.ruyi-20231207.amd64.tar.zst"
size = 3662953

[distfiles.checksums]
sha256 = "e664e202bce009dbf7e73d3ea0dca8c402868a1d6ec7cdcc35de2160c1c4dfc0"
sha512 = "d2f241aa60d7c4cf8373f941f6e8eef5197cdf5d6daf1aa984c163be0f2f452d508ed960264b498c29b89346c0edba18cef54db2a1067868f88c524e649aab28"

[[binary]]
host = "x86_64"
distfiles = ["qemu-user-riscv-xthead-6.1.0.ruyi-20231207.amd64.tar.zst"]

[emulator]
flavors = ["xthead"]

[[emulator.programs]]
path = "bin/qemu-riscv32"
flavor = "qemu-linux-user"
supported_arches = ["riscv32"]
binfmt_misc = ":ruyi-qemu-riscv32-xthead:M::\\x7fELF\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:$BIN:OCF"

[[emulator.programs]]
path = "bin/qemu-riscv64"
flavor = "qemu-linux-user"
supported_arches = ["riscv64"]
binfmt_misc = ":ruyi-qemu-riscv64-xthead:M::\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:$BIN:OCF"
