format = "v1"

[metadata]
desc = "Armbian 24.8.0-trunk.6 image for Pine64 Star64"
vendor = { name = "Armbian", eula = "" }

[[distfiles]]
name = "Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img.xz"
size = 214923876
urls = [
  "https://github.com/armbian/community/releases/download/24.8.0-trunk.6/Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img.xz"
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "bb67aa18093b2f11fdecf217bc49927b56542b0c44f86633fe53f4221a52537d"
sha512 = "fbb237d248980d2a85630a933c36ddc89cd527c0afad050995c1cb9dbb99d15e96fba1f12715f50e3fbd3f6e81b0ea8dccf44d1f70dabf9117508ff498d46dd9"

[blob]
distfiles = [
  "Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img"
