format = "v1"

[metadata]
desc = "RuyiSDK RISC-V Linux GNU Toolchain 20231118 (Upstream sources, built by PLCT)"
vendor = { name = "PLCT", eula = "" }
slug = "gnu-upstream-20231118"

[[distfiles]]
name = "RuyiSDK-20231118-Upstream-Sources-HOST-riscv64-linux-gnu-riscv64-unknown-linux-gnu.tar.xz"
size = 235357684

[distfiles.checksums]
sha256 = "7b03f67ed68eae7fcfcf377bac1429ffa4633131a3fefcd4f7de48bae8ede4cc"
sha512 = "1a3f0a1640a19b970886f9fdfb16e12ccde2e566c16820274ea4a9493513826f2e910dded1ae85c57db03e462963049fe231cc9d3d8220f7f6c1b29ef4746ef9"

[[distfiles]]
name = "RuyiSDK-20231118-Upstream-Sources-riscv64-unknown-linux-gnu.tar.xz"
size = 243532996

[distfiles.checksums]
sha256 = "48e286ed606378ded41d93502855bf8f6c626ec23285c7db616877c6eb62a09a"
sha512 = "f73ef9cfb7ac887a29ae73a8062e24ab314b1331003c2f3c504fc435d6e1e74e2aceba813d7de56943a029020b934f59838d8217058b6baa024b4acb725f5110"

[[binary]]
host = "riscv64"
distfiles = ["RuyiSDK-20231118-Upstream-Sources-HOST-riscv64-linux-gnu-riscv64-unknown-linux-gnu.tar.xz"]

[[binary]]
host = "x86_64"
distfiles = ["RuyiSDK-20231118-Upstream-Sources-riscv64-unknown-linux-gnu.tar.xz"]

[toolchain]
target = "riscv64-unknown-linux-gnu"
flavors = []
components = [
  { name = "binutils", version = "2.40" },
  { name = "gcc", version = "13.2.0" },
  { name = "gdb", version = "13.2" },
  { name = "glibc", version = "2.38" },
  { name = "linux-headers", version = "6.4" },
]
included_sysroot = "riscv64-unknown-linux-gnu/sysroot"
