format = "v1"

[metadata]
desc = "openEuler 23.09 v1 XFCE image for SiFive HiFive Unmatched"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "openEuler-23.09-V1-xfce-unmatched-preview.img.zst"
size = 1840898762
urls = [
  "https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/Unmatched/openEuler-23.09-V1-xfce-unmatched-preview.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8a79688c41463a11b58868ba5a7b6cba578f224ef27aed86912f3e3d5ca1514a"
sha512 = "6e19847db8bea1615ae7cb75ff4e266f681249ec8ac8de21a378b2f55a44f6ccd34ba0891e40e7fd5f1fd749695b14eda1135afa55ba5b90573ec68495ea8e23"

[blob]
distfiles = [
  "openEuler-23.09-V1-xfce-unmatched-preview.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "openEuler-23.09-V1-xfce-unmatched-preview.img"
