format = "v1"

[metadata]
desc = "openEuler 23.09 v1 headless image for SiFive HiFive Unmatched"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "openEuler-23.09-V1-base-unmatched-preview.img.zst"
size = 1174706940
urls = [
  "https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/Unmatched/openEuler-23.09-V1-base-unmatched-preview.img.zst",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "5cf24e3c80506677aae5660c8a50ea1b73b946b1ded9eeeb91fb88e165572021"
sha512 = "ac3060fa4eb64548199a72e9d8205685f6cf811d378578dd5d714a94dbf8e9d0faa792e77e649ba6f9dd4b65c84d1d4eae54702486627b50a12d46d9cdc4671e"

[blob]
distfiles = [
  "openEuler-23.09-V1-base-unmatched-preview.img.zst",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "openEuler-23.09-V1-base-unmatched-preview.img"
