ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc"]
unique_among_type_during_traversal = true

[device]
id = "awol-d1dev"
display_name = "Allwinner Nezha D1"

[[device.variants]]
id = "generic"
display_name = "Allwinner Nezha D1 (generic variant)"
