ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc"]
unique_among_type_during_traversal = true

[device]
id = "canaan-k230d"
display_name = "Canaan Kendryte K230D"

[[device.variants]]
id = "generic"
display_name = "Canaan Kendryte K230D (generic variant)"
