ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc"]
unique_among_type_during_traversal = true

[device]
id = "milkv-mars"
display_name = "Milk-V Mars"

[[device.variants]]
id = "generic"
display_name = "Milk-V Mars (generic variant)"
