ruyi-entity = "v0"

related = [
  "device-variant:milkv-meles@4g",
  "device-variant:milkv-meles@8g",
  "device-variant:milkv-meles@16g",
]
unique_among_type_during_traversal = true

[device]
id = "milkv-meles"
display_name = "Milk-V Meles"
