ruyi-entity = "v0"

related = ["cpu:xuantie-th1520"]
unique_among_type_during_traversal = true

[device]
id = "sipeed-lc4a"
display_name = "Sipeed Lichee Cluster 4A"

[[device.variants]]
id = "8g"
display_name = "Sipeed Lichee Cluster 4A (8G RAM)"

[[device.variants]]
id = "16g"
display_name = "Sipeed Lichee Cluster 4A (16G RAM)"
