ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc"]
unique_among_type_during_traversal = true

[device]
id = "sipeed-licheervnano"
display_name = "Sipeed LicheeRV Nano"

[[device.variants]]
id = "generic"
display_name = "Sipeed LicheeRV Nano (generic variant)"
