ruyi-entity = "v0"

# FIXME: Check and update with the correct CPU
related = ["cpu:generic-rv64gc"]
unique_among_type_during_traversal = true

[device]
id = "starfive-visionfive2"
display_name = "StarFive VisionFive2"

[[device.variants]]
id = "generic"
display_name = "StarFive VisionFive2 (generic variant)"
