ruyi-entity = "v0"

related = [
  "device-variant:wch-ch32v307-evb@rct6",
  "device-variant:wch-ch32v307-evb@vct6",
  "device-variant:wch-ch32v307-evb@wcu6", 
]
unique_among_type_during_traversal = true

[device]
id = "wch-ch32v307-evb"
display_name = "WCH CH32V307 EVB"
