ruyi-entity = "v0"

related = [
  "device-variant:wch-ch32v303-evb@cbt6",
  "device-variant:wch-ch32v303-evb@rbt6",
  "device-variant:wch-ch32v303-evb@rct6",
  "device-variant:wch-ch32v303-evb@vct6",
]

unique_among_type_during_traversal = true

[device]
id = "wch-ch32v303-evb"
display_name = "WCH CH32V303 EVB"
