format = "v1"

[metadata]
desc = "Kingsoft WPS Office"
vendor = { name = "Kingsoft", eula = "" }  # TODO: there is EULA but no link

[[distfiles]]
name = "wps-office_12.1.0.17885_amd64.deb"
size = 463718988
urls = []
restrict = ["fetch", "mirror"]

[distfiles.fetch_restriction]
msgid = "extras/wps-office"

[distfiles.fetch_restriction.params]
arch = "amd64"
arch_humanized = "X64"
version = "12.1.0.17885"

[distfiles.checksums]
sha256 = "b427df85ebf1067a4d8a7d6a041d8f4f238fa46bcf2e5234a962c20b2925b625"
sha512 = "ecefae6473719a2e8e2ffb50f756ac000b1b742bfa5e69fd40e22f515c97f6230f0ce67472a14caff2e194e1210d826496a698db259d603e30b9652f62c293b9"

[[binary]]
host = "x86_64"
distfiles = ["wps-office_12.1.0.17885_amd64.deb"]
