format = "v1"

[metadata]
desc = "RuyiSDK QEMU System Emulator Build (Upstream 8.2.0, built by PLCT)"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "qemu-system-riscv-upstream-8.2.0.ruyi-20240128.amd64.tar.zst"
size = 86351325

[distfiles.checksums]
sha256 = "b17bf2d3af9ae5fd43fedaba5925d552004f36a861ea7c6df22c06023ac44e6f"
sha512 = "afe8fffab4e2bd14a4809fef7a9caf867d6fe0cda7f5f0d612c94b5712380cd8b4a78989a7e6df7cb2ead78cf9caf177ff112d7d9057235509a215efc667d231"

[[binary]]
host = "x86_64"
distfiles = ["qemu-system-riscv-upstream-8.2.0.ruyi-20240128.amd64.tar.zst"]

[emulator]
flavors = []

[[emulator.programs]]
path = "bin/qemu-system-riscv32"
flavor = "qemu-system"
supported_arches = ["riscv32"]

[[emulator.programs]]
path = "bin/qemu-system-riscv64"
flavor = "qemu-system"
supported_arches = ["riscv64"]
