format = "v1"

[metadata]
desc = "Official CanMV Debian SDK v1.3 image for Canaan Kendryte K230"
vendor = { name = "Canaan", eula = "" }

[[distfiles]]
name = "canmv_debian_sdcard_sdk_1.3.img.gz"
size = 219982403
urls = [
  "https://kendryte-download.canaan-creative.com/developer/k230/canmv_debian_sdcard_sdk_1.3.img.gz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "a24278cf068cf080f80e08bd7c779b8c5cf7966f19ab8f8c7046cbd8bc6404af"
sha512 = "3f5a462bfbcb1b26dc466f65889fa679682326adba3f75406eece36d27441ec9b66789d0af49dd237aae630924f8ea0cc9e38a834c5400e3a888ccd7cabdfaae"

[blob]
distfiles = [
  "canmv_debian_sdcard_sdk_1.3.img.gz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "canmv_debian_sdcard_sdk_1.3.img"
