format = "v1"

[metadata]
desc = "RuyiSDK QEMU linux-user Build (Upstream 8.1.2, built by PLCT)"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "qemu-user-riscv-8.1.2.ruyi-20231121.amd64.tar.zst"
size = 15154068
strip_components = 2

[distfiles.checksums]
sha256 = "24b477630c5f9a01f8a2188e6b1a33bc24723d5217d34285a3bb3509f5a0948a"
sha512 = "73ac9c82b4386b5d8cb3d5e6654f600e38a7af6043bd546c7a0ec2940add29382a08f6a769bf1d5db150966dd18224789362add691c89c4e89ea31ae24436bd2"

[[binary]]
host = "x86_64"
distfiles = ["qemu-user-riscv-8.1.2.ruyi-20231121.amd64.tar.zst"]

[emulator]
flavors = []

[[emulator.programs]]
path = "bin/qemu-riscv32"
flavor = "qemu-linux-user"
supported_arches = ["riscv32"]
binfmt_misc = ":ruyi-qemu-riscv32:M::\\x7fELF\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:$BIN:OCF"

[[emulator.programs]]
path = "bin/qemu-riscv64"
flavor = "qemu-linux-user"
supported_arches = ["riscv64"]
binfmt_misc = ":ruyi-qemu-riscv64:M::\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:$BIN:OCF"
