format = "v1"

[metadata]
desc = "RuyiSDK QEMU linux-user Build (Upstream 8.2.0, built by PLCT)"
vendor = { name = "PLCT", eula = "" }

[[distfiles]]
name = "qemu-user-riscv-upstream-8.2.0.ruyi-20240128.amd64.tar.zst"
size = 15296197

[distfiles.checksums]
sha256 = "68d50e5001108e1d0bb1b5424aff47bf29d34aced16c85d728b0279a8cd78b47"
sha512 = "d3d17a1ca0e2b6424d9e2e9020542bcb5fb1b47ba97da3562e7bea5d87259f4e8f9d6eb06953453e028b586798f3a6d3ca7adc83189970b77e744f76b6436943"

[[binary]]
host = "x86_64"
distfiles = ["qemu-user-riscv-upstream-8.2.0.ruyi-20240128.amd64.tar.zst"]

[emulator]
flavors = []

[[emulator.programs]]
path = "bin/qemu-riscv32"
flavor = "qemu-linux-user"
supported_arches = ["riscv32"]
binfmt_misc = ":ruyi-qemu-riscv32:M::\\x7fELF\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:$BIN:OCF"

[[emulator.programs]]
path = "bin/qemu-riscv64"
flavor = "qemu-linux-user"
supported_arches = ["riscv64"]
binfmt_misc = ":ruyi-qemu-riscv64:M::\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00:\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:$BIN:OCF"
