format = "v1"

[metadata]
desc = "RuyiSDK RISC-V Linux GNU Toolchain 20231118 (maintained by PLCT)"
vendor = { name = "PLCT", eula = "" }
slug = "gnu-plct-20231118"

[[distfiles]]
name = "RuyiSDK-20231118-PLCT-Sources-riscv64-plct-linux-gnu.tar.xz"
size = 243656600

[distfiles.checksums]
sha256 = "c3d9c10b47abdc79ed55ee6dd7ecfd04cd8efe2763f0130c726581a31fd22120"
sha512 = "6201f9cba323acdc98ad411a9c13944fb35e85faf8cd985f552e5aff05c02c1d60fff4f5d651823089e64b305e6ba77b75c53c9fc599cc3776d90cf493dacc4f"

[[distfiles]]
name = "RuyiSDK-20231118-PLCT-Sources-HOST-riscv64-linux-gnu-riscv64-plct-linux-gnu.tar.xz"
size = 235503244

[distfiles.checksums]
sha256 = "5536741b8de9ae844143db88fb7c31576631873d5981b6b42fc21ca9a354b730"
sha512 = "a24568459b88595117e0646e076d55d7681cf09b842938b3d0bf8ec827ce336fe233eedf3b58cd65c6e78d8efcf097a9da536697ae1489fe07fa4bf182d8f49d"

[[binary]]
host = "riscv64"
distfiles = ["RuyiSDK-20231118-PLCT-Sources-HOST-riscv64-linux-gnu-riscv64-plct-linux-gnu.tar.xz"]

[[binary]]
host = "x86_64"
distfiles = ["RuyiSDK-20231118-PLCT-Sources-riscv64-plct-linux-gnu.tar.xz"]

[toolchain]
target = "riscv64-plct-linux-gnu"
flavors = []
components = [
  { name = "binutils", version = "2.40" },
  { name = "gcc", version = "13.1.0" },
  { name = "gdb", version = "13.1" },
  { name = "glibc", version = "2.38" },
  { name = "linux-headers", version = "6.4" },
]
included_sysroot = "riscv64-plct-linux-gnu/sysroot"
